version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    depends_on:
      - rabbitmq
      - mongodb
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./.data/db:/data/db